### PR TITLE
Updated project to use new Java 8 java.time.ZonedDateTime as time representation

### PR DESCRIPTION
**Pull request by 1tchy**
I'd like to use this library in a project of mine, but I don't like the old Date and Calendar. So I ported it to ZonedDateTime. Feel free to include it if you want!
I tried not to change anything functional, I hope I got that.

### CODE REVIEW

**Comment by dustmachine** [comment]
Interesting.  Yes, we should incorporate Java 8 somehow (and make dates easier) though I originally chose non-8 to be more inclusive and compatible.  We may just declare Java 8 to be the new/currently supported version and anyone wanting compatibility could use the older one, or an older "compatibility" branch.

**Comment by damon140** [comment]
Oh fab, an exciting pull request!

Android 5 is still at JDK 7, but there is a JSR-310 backport called
ThreeTen. This provides a different namespace though.

Perhaps we could make an Android branch of the current code, but then in
the future use the backport?

Java 6 compatible Android 4.4 is at %38 market share, so we might needed to
wait a few years on that branch.

D.

**Comment by 1tchy** [comment]
I think this project is not only interesting for Android development but also for others. I've not heard any objections yet, so will it be merged?

**Comment by dustmachine** [comment]
Yes, though I'm checking if I can merge this into the "develop" branch without making you resubmit the pull request. (We have started using the git-flow model http://danielkummer.github.io/git-flow-cheatsheet/). I will create a separate branch to maintain android compatibility.

**Comment by dustmachine** [comment]
Could I have you just resubmit the pull request to merge with the "develop" branch?  Also one minor thing - please set the version to "0.3.0-SNAPSHOT" until we create the release.   With git-flow, primary development happens on the "devlop" branch.

**Comment by dustmachine** [comment]
Closing this pull request in favor of the one done into the "develop" branch.  The changes will live in the "develop" branch while we get it all tested (and possibly put on a CI server!) at which point we will merge it into master.  Thank you for the update!

**Pull request closed without merging**
